# Utilisation de l'image officielle PHP Apache
FROM php:8.3-apache

ENV COMPOSER_ALLOW_SUPERUSER=1

# Expose le port 80 pour Apache
EXPOSE 80

# Définit le répertoire de travail
WORKDIR /app

# Installe git, unzip & zip pour composer et libpq-dev pour PDO PostgreSQL
RUN apt-get update -qq && \
    apt-get install -qy \
    git \
    gnupg \
    unzip \
    zip \
    libpq-dev && \
    docker-php-ext-install pdo pdo_mysql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copie le fichier de configuration PHP
COPY conf/php.ini /usr/local/etc/php/conf.d/app.ini

# Copie les fichiers de configuration Apache
COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY conf/apache.conf /etc/apache2/conf-available/library-app.conf

# Active les modules Apache et les configurations
RUN a2enmod rewrite remoteip && \
    a2enconf library-app

# Activer le virtual host
RUN a2ensite 000-default

# Copie les fichiers de l'application dans le conteneur
COPY app/ /var/www/html/

# Redémarre Apache pour appliquer les modifications
RUN service apache2 restart
