services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7000:80"
    volumes:
      - ${PWD}/app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${PWD}/mysql-data:/var/lib/mysql
      - ${PWD}/db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: